### ISSUE TITLE
Kompilierte exe statt vbs anbieten

### ISSUE THREAD

**Issue by beerisgood** [linuzer/HardlinkBackup#3]
Ist es möglich dein Script als fertig startende Exe anzubieten und die Einstellungen einfach aus einer .txt oder .ini auszulesen?
Gerade in sicheren Umgebungen ist das ausführen von .vbs nicht möglich und daher das Script nicht nutzbar

**Comment by beerisgood** [comment]
*push*

**Comment by beerisgood** [comment]
*Push*

**Comment by linuzer** [comment]
Möglich ist das ;-)

Aber leider im Moment nicht mir, da ich zeitlich in anderen Projekten gebunden bin. Aber fühl dich frei einen Fork zu machen, oder einen PR zusammen zu stellen...
